import XCTest
@testable import AltimCore

/// The Swift engine must give exactly the same results as the web engine (holdings.ts).
/// The reference file is generated by `web/test/holdings.test.ts`.
final class HoldingsParityTests: XCTestCase {
    struct TSCandle: Decodable { let time: Double; let open, high, low, close, volume: Double }
    struct TSSignal: Decodable { let action: SignalAction; let score: Double }
    struct TSMarket: Decodable { let price: Double; let daily: [TSCandle]; let daySignal: TSSignal?; let shortSignal: TSSignal?; let reliability: ReliabilityLevel? }
    struct TSCase: Decodable {
        let name: String
        let holdings: [Holding]
        let cash: Double
        let market: [String: TSMarket]
        let expected: HoldingsAnalyzer.Analysis
    }

    func testMatchesTypeScriptEngine() throws {
        let url = URL(fileURLWithPath: #filePath).deletingLastPathComponent().appendingPathComponent("holdings-fixture.json")
        let cases = try JSONDecoder().decode([TSCase].self, from: Data(contentsOf: url))
        XCTAssertEqual(cases.count, 4)
        for c in cases {
            let market = c.market.mapValues { m in
                HoldingsAnalyzer.MarketInput(
                    price: m.price,
                    daily: m.daily.map { Candle(time: Date(timeIntervalSince1970: $0.time / 1000), open: $0.open, high: $0.high, low: $0.low, close: $0.close, volume: $0.volume) },
                    daySignal: m.daySignal.map { .init(action: $0.action, score: $0.score) },
                    shortSignal: m.shortSignal.map { .init(action: $0.action, score: $0.score) },
                    reliability: m.reliability)
            }
            let a = HoldingsAnalyzer.analyze(holdings: c.holdings, cash: c.cash, market: market)
            let e = c.expected
            let tol = 1e-6
            XCTAssertEqual(a.total, e.total, accuracy: tol, c.name)
            XCTAssertEqual(a.pnl, e.pnl, accuracy: tol, c.name)
            XCTAssertEqual(a.allocation.crypto, e.allocation.crypto, accuracy: tol)
            XCTAssertEqual(a.allocation.cash, e.allocation.cash, accuracy: tol)
            XCTAssertEqual(a.lines.count, e.lines.count)
            for (l, x) in zip(a.lines, e.lines) {
                XCTAssertEqual(l.recommendation, x.recommendation, "\(c.name) \(l.symbol)")
                XCTAssertEqual(l.reasons, x.reasons, "\(c.name) \(l.symbol)")
                XCTAssertEqual(l.weight, x.weight, accuracy: tol)
                XCTAssertEqual(l.pnlPercent, x.pnlPercent, accuracy: tol)
                XCTAssertEqual(l.trimValue, x.trimValue, accuracy: tol)
                XCTAssertEqual(l.stop == nil, x.stop == nil)
                if let s = l.stop, let xs = x.stop { XCTAssertEqual(s, xs, accuracy: tol, "\(c.name) \(l.symbol) stop") }
            }
            func same(_ a: Double?, _ b: Double?, _ what: String) {
                XCTAssertEqual(a == nil, b == nil, "\(c.name) \(what)")
                if let a, let b { XCTAssertEqual(a, b, accuracy: tol, "\(c.name) \(what)") }
            }
            same(a.risk.volatilityAnnual, e.risk.volatilityAnnual, "volatilité")
            same(a.risk.var95Day, e.risk.var95Day, "VaR")
            same(a.risk.averageCorrelation, e.risk.averageCorrelation, "corrélation")
            XCTAssertEqual(a.risk.lossAtStops, e.risk.lossAtStops, accuracy: tol)
            XCTAssertEqual(a.risk.effectiveAssets, e.risk.effectiveAssets, accuracy: tol)
            XCTAssertEqual(a.insights.map(\.code), e.insights.map(\.code), c.name)
            XCTAssertEqual(a.insights.map(\.level), e.insights.map(\.level), c.name)
            for (i, x) in zip(a.insights, e.insights) {
                for (k, v) in x.values {
                    switch (i.values[k], v) {
                    case let (.number(p)?, .number(q)): XCTAssertEqual(p, q, accuracy: tol, "\(c.name) \(i.code).\(k)")
                    case let (.text(p)?, .text(q)): XCTAssertEqual(p, q)
                    default: XCTFail("\(c.name) \(i.code).\(k) différent")
                    }
                }
                XCTAssertFalse(HoldingsAnalyzer.text(i).isEmpty)
            }
        }
    }
}

final class HoldingsDatabaseTests: XCTestCase {
    func tempPath() -> String {
        FileManager.default.temporaryDirectory.appendingPathComponent("altim-\(UUID().uuidString).sqlite").path
    }

    func testCRUDAndMergeRecomputesAverageCost() async throws {
        let db = try HoldingsDatabase(path: ":memory:")
        let btc = try await db.upsert(Holding(symbol: "btc", kind: .crypto, name: "Bitcoin", quantity: 0.1, averagePrice: 60_000))
        XCTAssertEqual(btc.symbol, "BTC")
        // Second purchase: 0.1 at 80,000 → PRU 70,000 on 0.2.
        let merged = try await db.upsert(Holding(symbol: "BTC", kind: .crypto, name: "Bitcoin", quantity: 0.1, averagePrice: 80_000), merge: true)
        XCTAssertEqual(merged.id, btc.id)
        XCTAssertEqual(merged.quantity, 0.2, accuracy: 1e-12)
        XCTAssertEqual(merged.averagePrice, 70_000, accuracy: 1e-9)
        // Edit without merging: replaces.
        _ = try await db.upsert(Holding(id: btc.id, symbol: "BTC", kind: .crypto, name: "Bitcoin", quantity: 0.5, averagePrice: 50_000))
        _ = try await db.upsert(Holding(symbol: "AAPL", kind: .stock, name: "Apple", quantity: 10, averagePrice: 200))
        var all = try await db.all()
        XCTAssertEqual(all.map(\.symbol), ["BTC", "AAPL"])
        XCTAssertEqual(all[0].quantity, 0.5)
        try await db.delete(id: all[1].id)
        all = try await db.all()
        XCTAssertEqual(all.count, 1)
    }

    func testRejectsInvalidValues() async throws {
        let db = try HoldingsDatabase(path: ":memory:")
        for h in [Holding(symbol: "BTC", kind: .crypto, name: "B", quantity: 0, averagePrice: 1),
                  Holding(symbol: "BTC", kind: .crypto, name: "B", quantity: -1, averagePrice: 1),
                  Holding(symbol: "BTC", kind: .crypto, name: "B", quantity: .nan, averagePrice: 1),
                  Holding(symbol: "BTC", kind: .crypto, name: "B", quantity: 1, averagePrice: -5)] {
            do {
                _ = try await db.upsert(h)
                XCTFail("Valeur invalide acceptée")
            } catch {
                XCTAssertEqual(error as? HoldingsDatabaseError, .invalidHolding)
            }
        }
        do { try await db.setCash(-1); XCTFail() } catch {}
        let count = try await db.all().count
        XCTAssertEqual(count, 0)
    }

    func testPersistsAcrossReopenAndSchemaVersion() async throws {
        let path = tempPath()
        defer { try? FileManager.default.removeItem(atPath: path) }
        do {
            let db = try HoldingsDatabase(path: path)
            _ = try await db.upsert(Holding(symbol: "ETH", kind: .crypto, name: "Ethereum", quantity: 2, averagePrice: 3000))
            try await db.setCash(1500.5)
        }
        let reopened = try HoldingsDatabase(path: path)
        let all = try await reopened.all()
        let cash = try await reopened.cash()
        let version = try await reopened.schemaVersion()
        XCTAssertEqual(all.first?.symbol, "ETH")
        XCTAssertEqual(cash, 1500.5)
        XCTAssertEqual(version, HoldingsDatabase.migrations.count)
    }

    /// The export file of the Altim web app is imported as is into the iOS app (and vice versa).
    func testImportsWebExportAndRoundTrips() async throws {
        let web = #"""
        {"app":"altim","version":1,"cash":1500,"updatedAt":1790500000000,"holdings":[
          {"id":"cd2ede8b","symbol":"BTC","kind":"crypto","name":"Bitcoin","quantity":0.1,"averagePrice":60000},
          {"id":"a1","symbol":"AAPL","kind":"stock","name":"Apple Inc.","quantity":10,"averagePrice":200},
          {"id":"bad","symbol":"X","kind":"crypto","name":"X","quantity":0,"averagePrice":1}]}
        """#
        let db = try HoldingsDatabase(path: ":memory:")
        try await db.importJSON(Data(web.utf8))
        let all = try await db.all()
        XCTAssertEqual(all.map(\.symbol).sorted(), ["AAPL", "BTC"]) // invalid line ignored
        let cash = try await db.cash()
        XCTAssertEqual(cash, 1500)
        let exported = try await db.exportJSON()
        let other = try HoldingsDatabase(path: ":memory:")
        try await other.importJSON(exported)
        let again = try await other.all()
        XCTAssertEqual(Set(again.map(\.symbol)), ["AAPL", "BTC"])
    }

    func testInvalidImportLeavesDataUntouched() async throws {
        let db = try HoldingsDatabase(path: ":memory:")
        _ = try await db.upsert(Holding(symbol: "SOL", kind: .crypto, name: "Solana", quantity: 3, averagePrice: 100))
        do {
            try await db.importJSON(Data("pas du json".utf8))
            XCTFail("Import invalide accepté")
        } catch {
            XCTAssertEqual(error as? HoldingsDatabaseError, .invalidFile)
        }
        let count = try await db.all().count
        XCTAssertEqual(count, 1)
    }
}
